<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_jVmNkGAHEfGcMbyP-06ryQ" name="AdmisionHospitalizacion" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_jV36YGAHEfGcMbyP-06ryQ" name="Proceso de Admisión y Hospitalización">
      <elements xmi:type="process:Lane" xmi:id="_jWEHoGAHEfGcMbyP-06ryQ" name="Admisión" actor="_cyVDsG9DEfGBaZhoODUvOA">
        <elements xmi:type="process:StartEvent" xmi:id="_jWMDcGAHEfGcMbyP-06ryQ" name="Orden Recibida" outgoing="_jX4skGAHEfGcMbyP-06ryQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWMDcmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWMDcWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWMDc2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jWSxIGAHEfGcMbyP-06ryQ" name="Recepcionar orden de internamiento" outgoing="_jX_aQGAHEfGcMbyP-06ryQ" incoming="_jX4skGAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWSxImAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWSxIWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWSxI2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jWSxJGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jWSxJWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jWSxJmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jWSxKGAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jWSxJ2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jWSxKmAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEsGWyEfGwp_u9g6IG-Q" name="recepcionarOrdenDeInternamiento" content="47474405-c48e-48da-ac85-d03325640c27" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jWSxKWAHEfGcMbyP-06ryQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jWSxLGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jWZe0GAHEfGcMbyP-06ryQ" name="Verificar disponibilidad de camas" outgoing="_jYGH8GAHEfGcMbyP-06ryQ" incoming="_jX_aQGAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWZe0mAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWZe0WAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWZe02AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_IdTDMGi_EfGPqc2VPeDvjw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_IdTDMWi_EfGPqc2VPeDvjw" name="camaDisponible" content="camaDisponible" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_PyqHMGi_EfGPqc2VPeDvjw" name="camaDisponible" dataType="_jVm0oGAHEfGcMbyP-06ryQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_IdTDMmi_EfGPqc2VPeDvjw" name="hayCamaInput" content="hayCamaInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_oJPjoGjXEfGsF4eDmptGKw" name="hayCamaInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_oJPjoWjXEfGsF4eDmptGKw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_IdTDM2i_EfGPqc2VPeDvjw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jWZe1GAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jWZe1WAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jWZe1mAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jWZe2GAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jWZe12AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jWZe2mAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEsWWyEfGwp_u9g6IG-Q" name="verificarDisponibilidadDeCamas" content="bce63894-1023-4ab6-a3d2-63416a8f3bd9" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jWZe2WAHEfGcMbyP-06ryQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_GH__wGi_EfGPqc2VPeDvjw" name="hayCamaInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_GH__wWi_EfGPqc2VPeDvjw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jWZe3GAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_jWe-YGAHEfGcMbyP-06ryQ" name="¿Cama disponible?" outgoing="_jYLngGAHEfGcMbyP-06ryQ _jYZp8GAHEfGcMbyP-06ryQ" incoming="_jYGH8GAHEfGcMbyP-06ryQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWe-YmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWe-YWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWe-Y2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jWlFAGAHEfGcMbyP-06ryQ" name="Registrar en lista de espera" outgoing="_jYTjUGAHEfGcMbyP-06ryQ" incoming="_jYLngGAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWlFAmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWlFAWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWlFA2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PQTFYGjdEfGsF4eDmptGKw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PQTFYWjdEfGsF4eDmptGKw" name="hospitalizacion" content="hospitalizacion" type="TYPE_VARIABLE" returnType="com.company.model.Hospitalizacion">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RJn-gGjdEfGsF4eDmptGKw" name="hospitalizacion" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.Hospitalizacion"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PQTFYmjdEfGsF4eDmptGKw" name="newScript()" content="'EN_ESPERA'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_PQTFY2jdEfGsF4eDmptGKw" type="JAVA_METHOD" expression="setEstado">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jWlFBGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jWlFBWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jWlFBmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jWlFCGAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jWlFB2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jWlFCmAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEsmWyEfGwp_u9g6IG-Q" name="RegistrarEnListaDeEspera" content="5728a207-fb68-46c7-994c-25bc98d07784" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jWlFCWAHEfGcMbyP-06ryQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_NyMIoGjdEfGsF4eDmptGKw" name="notasEspera">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_NyMIoWjdEfGsF4eDmptGKw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jWlFDGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jWsZwGAHEfGcMbyP-06ryQ" name="En lista de espera" incoming="_jYTjUGAHEfGcMbyP-06ryQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWsZwmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWsZwWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWsZw2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jWxSQGAHEfGcMbyP-06ryQ" name="Facturación / Seguros" actor="_jGdUMG9DEfGBaZhoODUvOA">
        <elements xmi:type="process:XORGateway" xmi:id="_jXBJ4GAHEfGcMbyP-06ryQ" name="¿Cobertura validada?" outgoing="_jYoTcGAHEfGcMbyP-06ryQ _jYvBIGAHEfGcMbyP-06ryQ" incoming="_jYhlwGAHEfGcMbyP-06ryQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXBw8WAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXBw8GAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXBw8mAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jXHQgGAHEfGcMbyP-06ryQ" name="Trámite cancelado" incoming="_jYoTcGAHEfGcMbyP-06ryQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXHQgmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXHQgWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXHQg2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_YYbLsGjWEfGsF4eDmptGKw" name="Validar cobertura financiera SIS" outgoing="_jYhlwGAHEfGcMbyP-06ryQ" incoming="_jYZp8GAHEfGcMbyP-06ryQ" actor="_G4XloGWyEfGwp_u9g6IG-Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jW6cMmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jW6cMWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jW6cM2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_l85dUGjWEfGsF4eDmptGKw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_l85dUWjWEfGsF4eDmptGKw" name="coberturaValida" content="coberturaValida" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_odPTIGjWEfGsF4eDmptGKw" name="coberturaValida" dataType="_jVm0oGAHEfGcMbyP-06ryQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_l85dUmjWEfGsF4eDmptGKw" name="coberturaAprobadaInput" content="coberturaAprobadaInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qp7NIGjWEfGsF4eDmptGKw" name="coberturaAprobadaInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_qp7NIWjWEfGsF4eDmptGKw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_l85dU2jWEfGsF4eDmptGKw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jW6cNGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jW6cNWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jW6cNmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jW6cOGAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jW6cN2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_YYigeWjWEfGsF4eDmptGKw">
            <targetForm xmi:type="expression:Expression" xmi:id="_ty4iIGjWEfGsF4eDmptGKw" name="validarCoberturaFinancieraSIS" content="1ecc9339-f8d3-4fae-b8ff-67f2da15b476" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_YYigeGjWEfGsF4eDmptGKw">
            <inputs xmi:type="process:ContractInput" xmi:id="_jOYBkGjWEfGsF4eDmptGKw" name="coberturaAprobadaInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_jOYBkWjWEfGsF4eDmptGKw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_YYjHgGjWEfGsF4eDmptGKw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jXMJAGAHEfGcMbyP-06ryQ" name="Enfermería" actor="_k4f5kG9DEfGBaZhoODUvOA">
        <elements xmi:type="process:Task" xmi:id="_jXS2sGAHEfGcMbyP-06ryQ" name="Preparar cama y entorno" outgoing="_jY2V4GAHEfGcMbyP-06ryQ" incoming="_jYvBIGAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXTdwWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXTdwGAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXTdwmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_mVZ_wGjdEfGsF4eDmptGKw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mVZ_wWjdEfGsF4eDmptGKw" name="camaSeleccionada" content="camaSeleccionada" type="TYPE_VARIABLE" returnType="com.company.model.Cama">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MOIbQGjlEfGS3olz6yoYog" name="camaSeleccionada" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.Cama"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mVZ_wmjdEfGsF4eDmptGKw" name="codCamaAsignada" content="codCamaAsignada" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qQQrwGjdEfGsF4eDmptGKw" name="codCamaAsignada">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_qQQrwWjdEfGsF4eDmptGKw"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mVZ_w2jdEfGsF4eDmptGKw" type="JAVA_METHOD" expression="setCodigoCama">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jXTdw2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jXTdxGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jXTdxWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jXTdx2AHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jXTdxmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jXTdyWAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEs2WyEfGwp_u9g6IG-Q" name="prepararCamaYEntorno" content="f0fbaaac-0358-4e69-a762-76ef5a2b9571" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jXTdyGAHEfGcMbyP-06ryQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_lOvSoGjdEfGsF4eDmptGKw" name="codCamaAsignada">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_lOvSoWjdEfGsF4eDmptGKw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jXTdy2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jXY9UGAHEfGcMbyP-06ryQ" name="Trasladar e instalar paciente" outgoing="_jY_f0GAHEfGcMbyP-06ryQ" incoming="_jY2V4GAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXY9UmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXY9UWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXY9U2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jXY9VGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jXY9VWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jXY9VmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jXZkYWAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jXZkYGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jXZkY2AHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEtGWyEfGwp_u9g6IG-Q" name="newForm" content="d47e945a-a268-469a-9254-93e86b6e0520" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jXZkYmAHEfGcMbyP-06ryQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jXZkZWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_jXfD8GAHEfGcMbyP-06ryQ" name="Registrar signos vitales e ingreso" outgoing="_jZE_YGAHEfGcMbyP-06ryQ" incoming="_jY_f0GAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXfD8mAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXfD8WAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXfD82AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jXfD9GAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jXfD9WAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jXfD9mAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jXfD-GAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jXfD92AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jXfD-mAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEtWWyEfGwp_u9g6IG-Q" name="registrarSignosVitalesIngreso" content="a7a8625a-e6eb-4721-9bd8-1daf69246d0e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jXfD-WAHEfGcMbyP-06ryQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_xgUPcGjREfGsF4eDmptGKw" name="presionInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_xgUPcWjREfGsF4eDmptGKw"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_0GtC4GjREfGsF4eDmptGKw" name="temperaturaInput" type="DECIMAL">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_0GtC4WjREfGsF4eDmptGKw"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jXfD_GAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jXkjgGAHEfGcMbyP-06ryQ" name="Área Médica" actor="_n2Nn4G9DEfGBaZhoODUvOA">
        <elements xmi:type="process:Task" xmi:id="_jXtGYGAHEfGcMbyP-06ryQ" name="Aperturar HC y emitir plan médico" outgoing="_Ecp4wIwgEfGmMqDAR9OwHA" incoming="_jZE_YGAHEfGcMbyP-06ryQ" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXtGYmAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXtGYWAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXtGY2AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jXtGZGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jXtGZWAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jXtGZmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jXtGaGAHEfGcMbyP-06ryQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jXtGZ2AHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_jXtGamAHEfGcMbyP-06ryQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_5-pEtmWyEfGwp_u9g6IG-Q" name="newForm1" content="7736e001-45fe-47c8-91e6-acd92d8895d5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_jXtGaWAHEfGcMbyP-06ryQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_jXtGbGAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jXyl8GAHEfGcMbyP-06ryQ" name="Hospitalizado" incoming="_IEPqgIwgEfGmMqDAR9OwHA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jXyl8mAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jXyl8WAHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jXyl82AHEfGcMbyP-06ryQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_l_ytsIwfEfGmMqDAR9OwHA" name="Registrar Hospitalizacion en el sistema" outgoing="_Ez9lgIwgEfGmMqDAR9OwHA" incoming="_Ecp4wIwgEfGmMqDAR9OwHA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_l_6CcIwfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_l_5bYIwfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_l_6CcYwfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_4b38kIwhEfGmMqDAR9OwHA" name="PublicarSolicitudHospitalizacion" definitionId="rabbitmq-publish-message" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_4b38kYwhEfGmMqDAR9OwHA" definitionId="rabbitmq-publish-message" version="1.0.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38kowhEfGmMqDAR9OwHA" key="bootstrapServers">
                <expression xmi:type="expression:Expression" xmi:id="_4b38k4whEfGmMqDAR9OwHA" name="localhost:5672" content="localhost:5672" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38lIwhEfGmMqDAR9OwHA" key="rabbitmqUsername">
                <expression xmi:type="expression:Expression" xmi:id="_4b38lYwhEfGmMqDAR9OwHA" name="guest" content="guest" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38lowhEfGmMqDAR9OwHA" key="rabbitmqPassword">
                <expression xmi:type="expression:Expression" xmi:id="_4b38l4whEfGmMqDAR9OwHA" name="guest" content="guest" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38mIwhEfGmMqDAR9OwHA" key="rabbitmqVirtualHost">
                <expression xmi:type="expression:Expression" xmi:id="_4b38mYwhEfGmMqDAR9OwHA" name="/" content="/" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38mowhEfGmMqDAR9OwHA" key="rabbitmqSsl">
                <expression xmi:type="expression:Expression" xmi:id="_4b38m4whEfGmMqDAR9OwHA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38nIwhEfGmMqDAR9OwHA" key="exchange">
                <expression xmi:type="expression:Expression" xmi:id="_4b38nYwhEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38nowhEfGmMqDAR9OwHA" key="routingKey">
                <expression xmi:type="expression:Expression" xmi:id="_4b38n4whEfGmMqDAR9OwHA" name="solicitud_hospitalizacion" content="solicitud_hospitalizacion" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38oIwhEfGmMqDAR9OwHA" key="messageBody">
                <expression xmi:type="expression:Expression" xmi:id="_4b38oYwhEfGmMqDAR9OwHA" name="&lt;pattern-expression>" content="return '{&quot;numeroOrden&quot;: &quot;' + orden.numeroOrden + '&quot;, &quot;dniPaciente&quot;: &quot;' + paciente.dni + '&quot;, &quot;especialidad&quot;: &quot;' + orden.especialidad + '&quot;, &quot;codigoCama&quot;: &quot;' + camaSeleccionada.codigoCama + '&quot;}'" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38oowhEfGmMqDAR9OwHA" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_4b38o4whEfGmMqDAR9OwHA" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38pIwhEfGmMqDAR9OwHA" key="timeoutSeconds">
                <expression xmi:type="expression:Expression" xmi:id="_4b38pYwhEfGmMqDAR9OwHA" name="30" content="30" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4b38powhEfGmMqDAR9OwHA" key="maxRetries">
                <expression xmi:type="expression:Expression" xmi:id="_4b38p4whEfGmMqDAR9OwHA" name="3" content="3" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38qIwhEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38qYwhEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38qowhEfGmMqDAR9OwHA" name="success" content="success" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38q4whEfGmMqDAR9OwHA" name="success" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38rIwhEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38rYwhEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38rowhEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38r4whEfGmMqDAR9OwHA" name="errorMessage" content="errorMessage" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38sIwhEfGmMqDAR9OwHA" name="errorMessage" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38sYwhEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38sowhEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38s4whEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38tIwhEfGmMqDAR9OwHA" name="destination" content="destination" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38tYwhEfGmMqDAR9OwHA" name="destination" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38towhEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38t4whEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38uIwhEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38uYwhEfGmMqDAR9OwHA" name="partition" content="partition" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38uowhEfGmMqDAR9OwHA" name="partition" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38u4whEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38vIwhEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38vYwhEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38vowhEfGmMqDAR9OwHA" name="offset" content="offset" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Long">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38v4whEfGmMqDAR9OwHA" name="offset" type="java.lang.Long"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38wIwhEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_4b38wYwhEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_4b38wowhEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_4b38w4whEfGmMqDAR9OwHA" name="timestamp" content="timestamp" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Long">
                <referencedElements xmi:type="definition:Output" xmi:id="_4b38xIwhEfGmMqDAR9OwHA" name="timestamp" type="java.lang.Long"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_4b38xYwhEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_l_6CcowfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_l_6Cc4wfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_l_6CdIwfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_l_6CdowfEfGmMqDAR9OwHA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_l_6CdYwfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_18jsYIwfEfGmMqDAR9OwHA" name="Esperar confirmacion del backend" outgoing="_IEPqgIwgEfGmMqDAR9OwHA" incoming="_Ez9lgIwgEfGmMqDAR9OwHA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_18jsYowfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_18jsYYwfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_18jsY4wfEfGmMqDAR9OwHA" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Qb3f8IwkEfGmMqDAR9OwHA" name="ConsumirEventoHospitalizacion" definitionId="rabbitmq-consume-message" event="ON_ENTER" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Qb3f8YwkEfGmMqDAR9OwHA" definitionId="rabbitmq-consume-message" version="1.0.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f8owkEfGmMqDAR9OwHA" key="bootstrapServers">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f84wkEfGmMqDAR9OwHA" name="localhost:5672" content="localhost:5672" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f9IwkEfGmMqDAR9OwHA" key="rabbitmqUsername">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f9YwkEfGmMqDAR9OwHA" name="guest" content="guest" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f9owkEfGmMqDAR9OwHA" key="rabbitmqPassword">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f94wkEfGmMqDAR9OwHA" name="guest" content="guest" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f-IwkEfGmMqDAR9OwHA" key="rabbitmqVirtualHost">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f-YwkEfGmMqDAR9OwHA" name="/" content="/" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f-owkEfGmMqDAR9OwHA" key="rabbitmqSsl">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f-4wkEfGmMqDAR9OwHA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f_IwkEfGmMqDAR9OwHA" key="queue">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f_YwkEfGmMqDAR9OwHA" name="evento_hospitalizacion_completado" content="evento_hospitalizacion_completado" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3f_owkEfGmMqDAR9OwHA" key="autoAck">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3f_4wkEfGmMqDAR9OwHA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3gAIwkEfGmMqDAR9OwHA" key="timeoutSeconds">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3gAYwkEfGmMqDAR9OwHA" name="30" content="30" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Qb3gAowkEfGmMqDAR9OwHA" key="maxRetries">
                <expression xmi:type="expression:Expression" xmi:id="_Qb3gA4wkEfGmMqDAR9OwHA" name="3" content="3" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_Qb3gBIwkEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Qb3gBYwkEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Qb3gBowkEfGmMqDAR9OwHA" name="success" content="success" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_Qb3gB4wkEfGmMqDAR9OwHA" name="success" type="java.lang.Boolean"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Qb3gCIwkEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Qb3gCYwkEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Qb3gCowkEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Qb3gC4wkEfGmMqDAR9OwHA" name="errorMessage" content="errorMessage" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Qb3gDIwkEfGmMqDAR9OwHA" name="errorMessage" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Qb3gDYwkEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Qb3gDowkEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Qb3gD4wkEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Qb3gEIwkEfGmMqDAR9OwHA" name="messageCount" content="messageCount" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_Qb3gEYwkEfGmMqDAR9OwHA" name="messageCount" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Qb3gEowkEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Qb3gE4wkEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Qb3gFIwkEfGmMqDAR9OwHA" name="mensajeRecibidoTexto" content="mensajeRecibidoTexto" type="TYPE_VARIABLE" returnType="java.util.List">
                <referencedElements xmi:type="process:Data" xmi:id="_Qb3gFYwkEfGmMqDAR9OwHA" name="mensajeRecibidoTexto" multiple="true" dataType="_jVm0pWAHEfGcMbyP-06ryQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Qb3gFowkEfGmMqDAR9OwHA" name="messagesJson" content="messagesJson" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Qb3gF4wkEfGmMqDAR9OwHA" name="messagesJson" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Qb3gGIwkEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_Qb3gGYwkEfGmMqDAR9OwHA">
              <leftOperand xmi:type="expression:Expression" xmi:id="_Qb3gGowkEfGmMqDAR9OwHA"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_Qb3gG4wkEfGmMqDAR9OwHA" name="source" content="source" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_Qb3gHIwkEfGmMqDAR9OwHA" name="source" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_Qb3gHYwkEfGmMqDAR9OwHA" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_18jsZIwfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_18jsZYwfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_18jsZowfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_18jsaIwfEfGmMqDAR9OwHA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_18jsZ4wfEfGmMqDAR9OwHA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_pifgQGiwEfGPqc2VPeDvjw" name="paciente" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.Paciente2">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pifgQWiwEfGPqc2VPeDvjw" name="init_paciente()" content="def nuevoPaciente = new com.company.model.Paciente2()&#xD;&#xA;nuevoPaciente.dni = dniPaciente&#xD;&#xA;return nuevoPaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Paciente2">
          <referencedElements xmi:type="process:ContractInput" xmi:id="__KfakIwqEfGmMqDAR9OwHA" name="dniPaciente">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="__KfakYwqEfGmMqDAR9OwHA"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_y3Q3QGiwEfGPqc2VPeDvjw" name="orden" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.OrdenInternamiento">
        <defaultValue xmi:type="expression:Expression" xmi:id="_y3Q3QWiwEfGPqc2VPeDvjw" name="init_orden()" content="def nuevaOrden = new com.company.model.OrdenInternamiento()&#xD;&#xA;&#xD;&#xA;// Asignamos los datos del formulario a la BD&#xD;&#xA;// Usamos .toLong() en caso de que hayas cambiado el contrato a TEXT como te sugerí antes&#xD;&#xA;nuevaOrden.numeroOrden = numeroOrden.toLong()&#xD;&#xA;nuevaOrden.especialidad = especialidad&#xD;&#xA;nuevaOrden.medicoSolicitante = medicoSolicitante&#xD;&#xA;&#xD;&#xA;return nuevaOrden" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OrdenInternamiento">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Am434GjQEfGsF4eDmptGKw" name="numeroOrden">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_Am434WjQEfGsF4eDmptGKw"/>
          </referencedElements>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Am434mjQEfGsF4eDmptGKw" name="medicoSolicitante">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_Am4342jQEfGsF4eDmptGKw"/>
          </referencedElements>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Am435GjQEfGsF4eDmptGKw" name="especialidad">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_Am435WjQEfGsF4eDmptGKw"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1hnksGiwEfGPqc2VPeDvjw" name="camaSeleccionada" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.Cama">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1hnksWiwEfGPqc2VPeDvjw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_55EtIGiwEfGPqc2VPeDvjw" name="hospitalizacion" dataType="_jVm0qGAHEfGcMbyP-06ryQ" className="com.company.model.Hospitalizacion">
        <defaultValue xmi:type="expression:Expression" xmi:id="_55EtIWiwEfGPqc2VPeDvjw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_-x4kQGiyEfGPqc2VPeDvjw" name="coberturaValida" dataType="_jVm0oGAHEfGcMbyP-06ryQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_-x5LUGiyEfGPqc2VPeDvjw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_B_qH0GizEfGPqc2VPeDvjw" name="camaDisponible" dataType="_jVm0oGAHEfGcMbyP-06ryQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_B_qH0WizEfGPqc2VPeDvjw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_XRYYgIwfEfGmMqDAR9OwHA" name="mensajeRecibidoTexto" multiple="true" dataType="_jVm0pWAHEfGcMbyP-06ryQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_XRYYgYwfEfGmMqDAR9OwHA" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_jV4hf2AHEfGcMbyP-06ryQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZRjuAGWzEfGwp_u9g6IG-Q" name="inicioDelProceso" content="1c36c1fb-6365-4674-9bd9-79aac892194b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_jV4hgWAHEfGcMbyP-06ryQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_jV4hgmAHEfGcMbyP-06ryQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jX4skGAHEfGcMbyP-06ryQ" target="_jWSxIGAHEfGcMbyP-06ryQ" source="_jWMDcGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jX4skWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jX4skmAHEfGcMbyP-06ryQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jX_aQGAHEfGcMbyP-06ryQ" target="_jWZe0GAHEfGcMbyP-06ryQ" source="_jWSxIGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYABUGAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYABUWAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYGH8GAHEfGcMbyP-06ryQ" target="_jWe-YGAHEfGcMbyP-06ryQ" source="_jWZe0GAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYGH8WAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYGH8mAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYLngGAHEfGcMbyP-06ryQ" name="No" target="_jWlFAGAHEfGcMbyP-06ryQ" source="_jWe-YGAHEfGcMbyP-06ryQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYLngWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYLngmAHEfGcMbyP-06ryQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYTjUGAHEfGcMbyP-06ryQ" target="_jWsZwGAHEfGcMbyP-06ryQ" source="_jWlFAGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYTjUWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYTjUmAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYZp8GAHEfGcMbyP-06ryQ" name="Sí" target="_YYbLsGjWEfGsF4eDmptGKw" source="_jWe-YGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYZp8WAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYZp8mAHEfGcMbyP-06ryQ" name="newScript()" content="camaDisponible == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_sjHt8GjXEfGsF4eDmptGKw" name="camaDisponible" dataType="_jVm0oGAHEfGcMbyP-06ryQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYhlwGAHEfGcMbyP-06ryQ" target="_jXBJ4GAHEfGcMbyP-06ryQ" source="_YYbLsGjWEfGsF4eDmptGKw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYhlwWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYhlwmAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYoTcGAHEfGcMbyP-06ryQ" name="No" target="_jXHQgGAHEfGcMbyP-06ryQ" source="_jXBJ4GAHEfGcMbyP-06ryQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYoTcWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYoTcmAHEfGcMbyP-06ryQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jYvBIGAHEfGcMbyP-06ryQ" name="Sí" target="_jXS2sGAHEfGcMbyP-06ryQ" source="_jXBJ4GAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jYvBIWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jYvBImAHEfGcMbyP-06ryQ" name="newScript()" content="coberturaValida == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_UKxDAGjXEfGsF4eDmptGKw" name="coberturaValida" dataType="_jVm0oGAHEfGcMbyP-06ryQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jY2V4GAHEfGcMbyP-06ryQ" target="_jXY9UGAHEfGcMbyP-06ryQ" source="_jXS2sGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jY288GAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jY288WAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jY_f0GAHEfGcMbyP-06ryQ" target="_jXfD8GAHEfGcMbyP-06ryQ" source="_jXY9UGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jY_f0WAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jY_f0mAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jZE_YGAHEfGcMbyP-06ryQ" target="_jXtGYGAHEfGcMbyP-06ryQ" source="_jXfD8GAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jZE_YWAHEfGcMbyP-06ryQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jZE_YmAHEfGcMbyP-06ryQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ecp4wIwgEfGmMqDAR9OwHA" target="_l_ytsIwfEfGmMqDAR9OwHA" source="_jXtGYGAHEfGcMbyP-06ryQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ecp4wYwgEfGmMqDAR9OwHA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ecp4wowgEfGmMqDAR9OwHA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ez9lgIwgEfGmMqDAR9OwHA" target="_18jsYIwfEfGmMqDAR9OwHA" source="_l_ytsIwfEfGmMqDAR9OwHA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ez9lgYwgEfGmMqDAR9OwHA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ez9lgowgEfGmMqDAR9OwHA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IEPqgIwgEfGmMqDAR9OwHA" target="_jXyl8GAHEfGcMbyP-06ryQ" source="_18jsYIwfEfGmMqDAR9OwHA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IEPqgYwgEfGmMqDAR9OwHA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IEPqgowgEfGmMqDAR9OwHA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_G4XloGWyEfGwp_u9g6IG-Q" name="Empleado"/>
      <actors xmi:type="process:Actor" xmi:id="_cyVDsG9DEfGBaZhoODUvOA" name="ActorRecepcionista" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_jGdUMG9DEfGBaZhoODUvOA" name="ActorFacturacion"/>
      <actors xmi:type="process:Actor" xmi:id="_k4f5kG9DEfGBaZhoODUvOA" name="ActorEnfermeria"/>
      <actors xmi:type="process:Actor" xmi:id="_n2Nn4G9DEfGBaZhoODUvOA" name="ActorMedico"/>
      <contract xmi:type="process:Contract" xmi:id="_jV5IgGAHEfGcMbyP-06ryQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_Wcr3kGixEfGPqc2VPeDvjw" name="dniPaciente">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_WcseoGixEfGPqc2VPeDvjw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_arMfYGixEfGPqc2VPeDvjw" name="numeroOrden">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_arMfYWixEfGPqc2VPeDvjw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_dzpeEGixEfGPqc2VPeDvjw" name="especialidad">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_dzqFIGixEfGPqc2VPeDvjw"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_fnNGYGixEfGPqc2VPeDvjw" name="medicoSolicitante">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_fnNGYWixEfGPqc2VPeDvjw"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_jMFiYGixEfGPqc2VPeDvjw" expression="dniPaciente != null &amp;&amp; dniPaciente.matches(&quot;\\d{8}&quot;);" errorMessage="El DNI debe tener 8 dígitos" name="validarDni">
          <inputNames>dniPaciente</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jV4hcGAHEfGcMbyP-06ryQ">
        <name xmi:type="expression:Expression" xmi:id="_jV4hcWAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jV4hcmAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jV4hc2AHEfGcMbyP-06ryQ">
        <name xmi:type="expression:Expression" xmi:id="_jV4hdGAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jV4hdWAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jV4hdmAHEfGcMbyP-06ryQ">
        <name xmi:type="expression:Expression" xmi:id="_jV4hd2AHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jV4heGAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jV4heWAHEfGcMbyP-06ryQ">
        <name xmi:type="expression:Expression" xmi:id="_jV4hemAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jV4he2AHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_jV4hfGAHEfGcMbyP-06ryQ">
        <name xmi:type="expression:Expression" xmi:id="_jV4hfWAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_jV4hfmAHEfGcMbyP-06ryQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_jVm0oGAHEfGcMbyP-06ryQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_jVm0oWAHEfGcMbyP-06ryQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_jVm0omAHEfGcMbyP-06ryQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_jVm0o2AHEfGcMbyP-06ryQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_jVm0pGAHEfGcMbyP-06ryQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_jVm0pWAHEfGcMbyP-06ryQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_jVm0pmAHEfGcMbyP-06ryQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_jVm0p2AHEfGcMbyP-06ryQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_jVm0qGAHEfGcMbyP-06ryQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_jVmNkWAHEfGcMbyP-06ryQ" type="Process" element="_jVmNkGAHEfGcMbyP-06ryQ" name="Definitions_1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_jV5vkGAHEfGcMbyP-06ryQ" type="2007" element="_jV36YGAHEfGcMbyP-06ryQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_jV6WoGAHEfGcMbyP-06ryQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_jV6WoWAHEfGcMbyP-06ryQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_jWEusGAHEfGcMbyP-06ryQ" type="3007" element="_jWEHoGAHEfGcMbyP-06ryQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_jWEutWAHEfGcMbyP-06ryQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jWEutmAHEfGcMbyP-06ryQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jWMqgGAHEfGcMbyP-06ryQ" type="3002" element="_jWMDcGAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWNRkGAHEfGcMbyP-06ryQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jWNRkWAHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWMqgWAHEfGcMbyP-06ryQ" x="80" y="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWTYMGAHEfGcMbyP-06ryQ" type="3005" element="_jWSxIGAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWT_QGAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWTYMWAHEfGcMbyP-06ryQ" x="220" y="33" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWaF4GAHEfGcMbyP-06ryQ" type="3005" element="_jWZe0GAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWaF4mAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWaF4WAHEfGcMbyP-06ryQ" x="480" y="33" width="186" height="93"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWflcGAHEfGcMbyP-06ryQ" type="3008" element="_jWe-YGAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWflcmAHEfGcMbyP-06ryQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jWflc2AHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWflcWAHEfGcMbyP-06ryQ" x="760" y="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWlsEGAHEfGcMbyP-06ryQ" type="3005" element="_jWlFAGAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWlsEmAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWlsEWAHEfGcMbyP-06ryQ" x="930" y="15" width="198" height="99"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWtA0GAHEfGcMbyP-06ryQ" type="3003" element="_jWsZwGAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWtA0mAHEfGcMbyP-06ryQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jWtA02AHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWtA0WAHEfGcMbyP-06ryQ" x="1230" y="47"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jWEusWAHEfGcMbyP-06ryQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jWEusmAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jWEus2AHEfGcMbyP-06ryQ" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jWEut2AHEfGcMbyP-06ryQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWEutGAHEfGcMbyP-06ryQ" x="28" y="10" width="1837" height="185"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jWx5UGAHEfGcMbyP-06ryQ" type="3007" element="_jWxSQGAHEfGcMbyP-06ryQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_jWx5VWAHEfGcMbyP-06ryQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jWx5VmAHEfGcMbyP-06ryQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jXCYAGAHEfGcMbyP-06ryQ" type="3008" element="_jXBJ4GAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXCYAmAHEfGcMbyP-06ryQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jXCYA2AHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXCYAWAHEfGcMbyP-06ryQ" x="1010" y="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jXH3kGAHEfGcMbyP-06ryQ" type="3003" element="_jXHQgGAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXH3kmAHEfGcMbyP-06ryQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jXH3k2AHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXH3kWAHEfGcMbyP-06ryQ" x="1230" y="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YYmx4GjWEfGsF4eDmptGKw" type="3005" element="_YYbLsGjWEfGsF4eDmptGKw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YYnY8GjWEfGsF4eDmptGKw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YYmx4WjWEfGsF4eDmptGKw" x="720" y="30" width="182" height="91"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jWx5UWAHEfGcMbyP-06ryQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jWx5UmAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jWx5U2AHEfGcMbyP-06ryQ" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jWx5V2AHEfGcMbyP-06ryQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWx5VGAHEfGcMbyP-06ryQ" x="28" y="185" width="1837" height="181"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jXMwEGAHEfGcMbyP-06ryQ" type="3007" element="_jXMJAGAHEfGcMbyP-06ryQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_jXMwFWAHEfGcMbyP-06ryQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jXMwFmAHEfGcMbyP-06ryQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jXUr4GAHEfGcMbyP-06ryQ" type="3005" element="_jXS2sGAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXUr4mAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXUr4WAHEfGcMbyP-06ryQ" x="940" y="35" width="170" height="85"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jXZkZmAHEfGcMbyP-06ryQ" type="3005" element="_jXY9UGAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXaLcGAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXZkZ2AHEfGcMbyP-06ryQ" x="1190" y="35" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jXfrAGAHEfGcMbyP-06ryQ" type="3005" element="_jXfD8GAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXgSEGAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXfrAWAHEfGcMbyP-06ryQ" x="1440" y="35" width="184" height="92"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jXMwEWAHEfGcMbyP-06ryQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jXMwEmAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jXMwE2AHEfGcMbyP-06ryQ" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jXMwF2AHEfGcMbyP-06ryQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXMwFGAHEfGcMbyP-06ryQ" x="28" y="366" width="1837" height="180"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jXlKkGAHEfGcMbyP-06ryQ" type="3007" element="_jXkjgGAHEfGcMbyP-06ryQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_jXlKlWAHEfGcMbyP-06ryQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jXlKlmAHEfGcMbyP-06ryQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jXttcGAHEfGcMbyP-06ryQ" type="3005" element="_jXtGYGAHEfGcMbyP-06ryQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXttcmAHEfGcMbyP-06ryQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXttcWAHEfGcMbyP-06ryQ" x="932" y="36" width="194" height="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jXzNAGAHEfGcMbyP-06ryQ" type="3003" element="_jXyl8GAHEfGcMbyP-06ryQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jXzNAmAHEfGcMbyP-06ryQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jXzNA2AHEfGcMbyP-06ryQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXzNAWAHEfGcMbyP-06ryQ" x="1690" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l_-68IwfEfGmMqDAR9OwHA" type="3027" element="_l_ytsIwfEfGmMqDAR9OwHA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_l__iAIwfEfGmMqDAR9OwHA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l_-68YwfEfGmMqDAR9OwHA" x="1196" y="39" width="183" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_18k6gIwfEfGmMqDAR9OwHA" type="3027" element="_18jsYIwfEfGmMqDAR9OwHA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_18k6gowfEfGmMqDAR9OwHA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_18k6gYwfEfGmMqDAR9OwHA" x="1440" y="45" width="158" height="79"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jXlKkWAHEfGcMbyP-06ryQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jXlKkmAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jXlKk2AHEfGcMbyP-06ryQ" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jXlKl2AHEfGcMbyP-06ryQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jXlKlGAHEfGcMbyP-06ryQ" x="28" y="546" width="1837" height="185"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_jV5vkWAHEfGcMbyP-06ryQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_jV5vkmAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_jV5vk2AHEfGcMbyP-06ryQ" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_jV6WomAHEfGcMbyP-06ryQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jV5vlGAHEfGcMbyP-06ryQ" width="1865" height="665"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_jVmNkmAHEfGcMbyP-06ryQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_jX5ToGAHEfGcMbyP-06ryQ" type="4001" element="_jX4skGAHEfGcMbyP-06ryQ" source="_jWMqgGAHEfGcMbyP-06ryQ" target="_jWTYMGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jX5To2AHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jX5TpGAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jX5ToWAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jX5TomAHEfGcMbyP-06ryQ" points="[0, 0, -104, 0]$[104, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYABUmAHEfGcMbyP-06ryQ" type="4001" element="_jX_aQGAHEfGcMbyP-06ryQ" source="_jWTYMGAHEfGcMbyP-06ryQ" target="_jWaF4GAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYABVWAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYABVmAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYABU2AHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYABVGAHEfGcMbyP-06ryQ" points="[0, 0, -120, 0]$[120, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYGH82AHEfGcMbyP-06ryQ" type="4001" element="_jYGH8GAHEfGcMbyP-06ryQ" source="_jWaF4GAHEfGcMbyP-06ryQ" target="_jWflcGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYGH9mAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYGH92AHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYGH9GAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYGH9WAHEfGcMbyP-06ryQ" points="[0, 0, -140, 0]$[140, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYMOkGAHEfGcMbyP-06ryQ" type="4001" element="_jYLngGAHEfGcMbyP-06ryQ" source="_jWflcGAHEfGcMbyP-06ryQ" target="_jWlsEGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYMOk2AHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYMOlGAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYMOkWAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYMOkmAHEfGcMbyP-06ryQ" points="[0, 0, -140, 23]$[0, -23, -140, 0]$[140, -23, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYTjU2AHEfGcMbyP-06ryQ" type="4001" element="_jYTjUGAHEfGcMbyP-06ryQ" source="_jWlsEGAHEfGcMbyP-06ryQ" target="_jWtA0GAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYUKYmAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYUKY2AHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYUKYGAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYUKYWAHEfGcMbyP-06ryQ" points="[0, 0, -160, 0]$[160, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYaRAGAHEfGcMbyP-06ryQ" type="4001" element="_jYZp8GAHEfGcMbyP-06ryQ" source="_jWflcGAHEfGcMbyP-06ryQ" target="_YYmx4GjWEfGsF4eDmptGKw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYa4EGAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYa4EWAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYaRAWAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYaRAmAHEfGcMbyP-06ryQ" points="[0, 0, 0, -62]$[0, 62, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYiM0GAHEfGcMbyP-06ryQ" type="4001" element="_jYhlwGAHEfGcMbyP-06ryQ" source="_YYmx4GjWEfGsF4eDmptGKw" target="_jXCYAGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYiM02AHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYiM1GAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYiM0WAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYiM0mAHEfGcMbyP-06ryQ" points="[0, 0, -150, 0]$[150, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYoTc2AHEfGcMbyP-06ryQ" type="4001" element="_jYoTcGAHEfGcMbyP-06ryQ" source="_jXCYAGAHEfGcMbyP-06ryQ" target="_jXH3kGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYo6gGAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYo6gWAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYoTdGAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYoTdWAHEfGcMbyP-06ryQ" points="[0, 0, -160, 0]$[160, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jYvoMGAHEfGcMbyP-06ryQ" type="4001" element="_jYvBIGAHEfGcMbyP-06ryQ" source="_jXCYAGAHEfGcMbyP-06ryQ" target="_jXUr4GAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jYvoM2AHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jYvoNGAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jYvoMWAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jYvoMmAHEfGcMbyP-06ryQ" points="[0, 0, 0, -75]$[0, 75, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jY288mAHEfGcMbyP-06ryQ" type="4001" element="_jY2V4GAHEfGcMbyP-06ryQ" source="_jXUr4GAHEfGcMbyP-06ryQ" target="_jXZkZmAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jY3kAGAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jY3kAWAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jY2882AHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jY289GAHEfGcMbyP-06ryQ" points="[0, 0, -110, 0]$[110, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jY_f02AHEfGcMbyP-06ryQ" type="4001" element="_jY_f0GAHEfGcMbyP-06ryQ" source="_jXZkZmAHEfGcMbyP-06ryQ" target="_jXfrAGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jZAG4mAHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jZAG42AHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jZAG4GAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jZAG4WAHEfGcMbyP-06ryQ" points="[0, 0, -110, 0]$[110, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jZFmcGAHEfGcMbyP-06ryQ" type="4001" element="_jZE_YGAHEfGcMbyP-06ryQ" source="_jXfrAGAHEfGcMbyP-06ryQ" target="_jXttcGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_jZFmc2AHEfGcMbyP-06ryQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jZFmdGAHEfGcMbyP-06ryQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jZFmcWAHEfGcMbyP-06ryQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jZFmcmAHEfGcMbyP-06ryQ" points="[0, 46, 503, -137]$[0, 74, 503, -109]$[-503, 74, 0, -109]$[-503, 135, 0, -48]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ecqf0IwgEfGmMqDAR9OwHA" type="4001" element="_Ecp4wIwgEfGmMqDAR9OwHA" source="_jXttcGAHEfGcMbyP-06ryQ" target="_l_-68IwfEfGmMqDAR9OwHA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EcrG4IwgEfGmMqDAR9OwHA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EcrG4YwgEfGmMqDAR9OwHA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ecqf0YwgEfGmMqDAR9OwHA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ecqf0owgEfGmMqDAR9OwHA" points="[97, 6, -161, 5]$[167, 6, -91, 5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ez-MkIwgEfGmMqDAR9OwHA" type="4001" element="_Ez9lgIwgEfGmMqDAR9OwHA" source="_l_-68IwfEfGmMqDAR9OwHA" target="_18k6gIwfEfGmMqDAR9OwHA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ez-Mk4wgEfGmMqDAR9OwHA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ez-MlIwgEfGmMqDAR9OwHA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ez-MkYwgEfGmMqDAR9OwHA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ez-MkowgEfGmMqDAR9OwHA" points="[92, 0, -140, 1]$[153, 0, -79, 1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IEQRkIwgEfGmMqDAR9OwHA" type="4001" element="_IEPqgIwgEfGmMqDAR9OwHA" source="_18k6gIwfEfGmMqDAR9OwHA" target="_jXzNAGAHEfGcMbyP-06ryQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IEQRk4wgEfGmMqDAR9OwHA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IEQ4oIwgEfGmMqDAR9OwHA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IEQRkYwgEfGmMqDAR9OwHA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IEQRkowgEfGmMqDAR9OwHA" points="[37, 4, -107, -13]$[144, 31, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IERfsIwgEfGmMqDAR9OwHA" id="(0.7658227848101266,0.4430379746835443)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
